development:
  adapter: sqlite3
  database: database.db

test:
  adapter: sqlite3
  database: database.db

production:
  adapter: postgresql
  database: d8hvldpq3d4ock
  username: kkwphefkmktlbn
  password: a3a700f56ad25153522598488c8ba220a0f114114701cd85f97497e47b2a6216
  host: localhost
